- name:  Debian step 1 - Install packages
  apt:
    name: ['apt-transport-https','ca-certificates', 'curl', 'gnupg-agent', 'software-properties-common','default-jre','default-jdk']
    state: present
    update_cache: yes
    
    
- name: Debian step 2 - Add Docker’s official GPG key  
  apt_key:
      id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
      url: "https://download.docker.com/linux/ubuntu/gpg"
      state: present
  
  
- name: Debian step 3 - Download and create repo
  apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu  "{{ dist_release }}" stable
      state: present
  become_method: sudo
  
  
- name: Debian step 4 - Install Docker Engine
  apt:
    name: ['docker-ce', 'docker-ce-cli', 'docker-ce-cli']
    state: present
    update_cache: yes
  register: docker_engine
  
  
- name: Debian step 5 - Restart the docker service
  service:
      name: docker
      state: restarted
      enabled: yes
  when: docker_engine.changed
  
- name: Debian step 6 - Create the docker group
  group:
      name: docker
      state: present

- name: Changing permission of "/var/run/docker.sock", adding "+x"
  file: dest=/var/run/docker.sock mode=a+x

- name: Snap install kubectl
  snap:
    name: ['kubectl']
    state: present
    classic: true

- name: Add users to docker group.
  user:
    name: "{{ item }}"
    groups: docker
    append: true
  with_items: "{{ docker_group_user }}"